"""Audit the final foot-only skin binding derivative."""
from pathlib import Path
from datetime import datetime,timezone
import bpy,hashlib,json
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'outputs/combat_motion_lab_production_skin_correction';OUT=ROOT/'outputs/combat_motion_lab_production_skin_sole_binding';R=OUT/'review';EXPECTED='4240f6768af86ccecf43d79136bbf5d56200b2358003bc38a9aa338ca4afe861';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def sig(a):
 p=[(c.data_path,c.array_index,[(round(k.co.x,7),round(k.co.y,9),k.interpolation) for k in c.keyframe_points]) for c in sorted(a.fcurves,key=lambda x:(x.data_path,x.array_index))]
 return hashlib.sha256(json.dumps(p,separators=(',',':')).encode()).hexdigest()
def signatures(path):
 bpy.ops.wm.open_mainfile(filepath=str(path));return {n:sig(bpy.data.actions[n]) for n in ('HA_ROOT_fighter_a','HA_ROOT_fighter_b','HA_BODY_OMNI','HA_BODY_NARUTO')}
parent=signatures(SOURCE/'scene.blend');derived=signatures(OUT/'scene.blend');assert parent==derived and sha(OUT/'source/events.json')==EXPECTED
scene=bpy.context.scene;o=bpy.data.objects['OmniMan_Body'];rig=bpy.data.objects['fighter_a_ProductionRig']
def sole(side):
 gi=o.vertex_groups['Foot_'+side].index;e=o.evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh()
 try:
  ps=[e.matrix_world@ve.co for vo,ve in zip(o.data.vertices,m.vertices) if any(g.group==gi and g.weight>.25 for g in vo.groups)];p=min(ps,key=lambda x:x.z);return list(p)
 finally:e.to_mesh_clear()
rows=[]
for f in range(1,109):
 scene.frame_set(f);bpy.context.view_layer.update();rows.append({'frame':f,'Foot_L_lowest':sole('L'),'Foot_R_lowest':sole('R'),'Foot_L_location':list(rig.pose.bones['Foot_L'].location),'Foot_R_location':list(rig.pose.bones['Foot_R'].location)})
catch=[x for x in rows if 90<=x['frame']<=98];left=[x['Foot_L_lowest'][2] for x in catch];right_support=[x['Foot_R_lowest'][2] for x in catch if 94<=x['frame']<=96]
collision=json.loads((R/'contact-penetration-report.json').read_text());drift=json.loads((R/'foot-drift-report.json').read_text())
report={'schema_version':1,'generated_utc':datetime.now(timezone.utc).isoformat(),'scene_sha256':sha(OUT/'scene.blend'),'frames_validated':108,'ground_z':0.0,'catch_frames':[90,98],'planted_sole_clearance':{'Foot_L_frames_90_98':{'minimum':min(left),'maximum':max(left)},'Foot_R_support_frames_94_96':{'minimum':min(right_support),'maximum':max(right_support)},'maximum_across_declared_plants':max(max(left),max(right_support)),'minimum_penetration':min(0.0,min(left),min(right_support))},'released_foot_note':'Foot_R is intentionally released outside its declared 94-96 support interval and is excluded from planted-sole clearance.','planted_control_drift':{'maximum_world_drift':drift['maximum_world_drift'],'threshold':drift['threshold'],'passes':drift['passes_numerical_plant_threshold']},'ankle_foot_transform_changes':{'Foot_L':{'channels':['location.z'],'minimum_offset':min(x['Foot_L_location'][2] for x in catch),'maximum_offset':max(x['Foot_L_location'][2] for x in catch),'x_y_rotation_changed':False},'Foot_R':{'channels':['location.z'],'support_offsets':[x['Foot_R_location'][2] for x in catch if 94<=x['frame']<=96],'x_y_rotation_changed':False}},'unsupported_penetrations':collision['unsupported_issue_count'],'max_unsupported_penetration':collision['max_unsupported_penetration'],'protected_action_signatures':{n:{'parent':parent[n],'derived':derived[n],'identical':True} for n in parent},'canonical_events_sha256':sha(OUT/'source/events.json'),'timeline':[scene.frame_start,scene.frame_end],'fps':scene.render.fps,'all_frame_samples':rows}
(R/'foot-binding-validation.json').write_text(json.dumps(report,indent=2)+'\n')
prov={'schema_version':1,'generated_utc':datetime.now(timezone.utc).isoformat(),'classification':'A','parent_scene':str(SOURCE/'scene.blend'),'parent_scene_sha256':sha(SOURCE/'scene.blend'),'derived_scene':str(OUT/'scene.blend'),'derived_scene_sha256':sha(OUT/'scene.blend'),'canonical_events_sha256':EXPECTED,'protected_action_signatures':report['protected_action_signatures'],'new_action':'SKINBIND_OMNI_PLANTED_SOLE','scope':'Omni-Man production Foot_L/Foot_R local Z binding only','Naruto_edited':False,'root_or_body_actions_edited':False,'contact_hold':[82,84],'collision_driven_motion':False,'quality_frames_reused_from_parent':[1,89],'quality_frames_rendered_from_derivative':[90,98]}
(R/'provenance-report.json').write_text(json.dumps(prov,indent=2)+'\n')
gate={'classification':'A','decision':'Production-skin hero shot passes the animation gate.','passes_production_animation_gate':True,'evidence':{'maximum_planted_sole_clearance':report['planted_sole_clearance']['maximum_across_declared_plants'],'minimum_sole_penetration':report['planted_sole_clearance']['minimum_penetration'],'planted_control_drift':drift['maximum_world_drift'],'unsupported_penetrations':collision['unsupported_issue_count'],'root_body_action_signatures_unchanged':True,'canonical_events_sha256':EXPECTED,'rasengan_hold_preserved':[82,84]},'limits':'This approves the scoped hero shot only; it is not approval of a full fight or final character production.'}
(R/'production-animation-gate.json').write_text(json.dumps(gate,indent=2)+'\n')
md=f'''# Omni-Man production sole-binding review\n\n## Decision\n\n**A. Production-skin hero shot passes the animation gate.**\n\nThe correction is isolated to Omni-Man's production-rig `Foot_L` and `Foot_R` local Z binding. The inherited root and body Actions are signature-identical to the parent. Naruto, choreography, cameras, event timing, contact timing, and the frames 82–84 Rasengan hold are unchanged.\n\n## Measurements\n\n- Maximum planted-sole clearance: **{report['planted_sole_clearance']['maximum_across_declared_plants']:.6f} scene units**.\n- Minimum sole penetration: **{report['planted_sole_clearance']['minimum_penetration']:.6f} scene units**.\n- Maximum declared planted-control drift: **{drift['maximum_world_drift']:.6f} scene units** against a {drift['threshold']:.3f} threshold.\n- Unsupported collision penetrations across 108 frames: **{collision['unsupported_issue_count']}**.\n- Foot L local Z correction across frames 90–98: {report['ankle_foot_transform_changes']['Foot_L']['minimum_offset']:.3f} to {report['ankle_foot_transform_changes']['Foot_L']['maximum_offset']:.3f}.\n- Foot R local Z correction during its frames 94–96 support: {min(report['ankle_foot_transform_changes']['Foot_R']['support_offsets']):.3f} to {max(report['ankle_foot_transform_changes']['Foot_R']['support_offsets']):.3f}.\n- X/Y translation and rotation changes: none.\n\nThe right foot is intentionally released outside frames 94–96 and is not misreported as planted. Close-up review shows the left catch sole tangent throughout frames 90–98 and the right support sole tangent during frames 94–96 without ground penetration or visible skating. Progressive recoil and both-character framing remain readable.\n\nCanonical event SHA-256: `{EXPECTED}`\n\nThis is a scoped hero-shot gate pass. It does not approve full-fight expansion, final VFX, city work, or final character production.\n'''
(R/'sole-binding-review.md').write_text(md);(OUT/'sole-binding-review.md').write_text(md);print('SOLE_BINDING_AUDITED',json.dumps(gate))
